# myName = input("What's you name?: ")
# myAge = input("How old are you? :")
# print("Gee, that's REALLY OLD")
# replit = input("Do you like Replit?")
# print("OF COURSE YOU DO!")

# print()
# print("So, you are")
# print(myName)
# print("and are the ripe old age of")
# print(myAge)
# print("and clearly think that Replit is")
# print(replit)

# print("Definitely not a Phishing Scam")
# print()
# myName = input("Your Name")
# print("Thanks for logging in")
# print(myName)
# cardNumber = input("What is your credit card number?")
# print("Thanks, I definitely wont put")
# print(cardNumber)
# print("into Amazon and order anything weird")
# print()
# print("Promise")
# maidenName = input("What is your Mother's maiden name? ")
# print()
# print("That's cool, I just wanted to know that")
# print(maidenName)
# print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

yourName = input("What is your name? ")
favFood = input("What is your favorite food?")
favMusic = input("What is your favorite music?")
location = input("Where do you live?")

print()
print("You are")
print(yourName)
print("You're probably hungry for")
print(favFood)
print("and you're definitely getting your groove on to")
print(favMusic)
print("living in the amazing")
print(location)
